-- vim.keymap.set("i", "đ", "]", { buffer = 0 })
-- vim.keymap.set("i", "š", "[", { buffer = 0 })
-- vim.keymap.set("i", "<S-Đ>", "}", { buffer = 0 })
-- vim.keymap.set("i", "<S-Š>", "{", { buffer = 0 })

local pairs = require("mini.pairs")
pairs.map_buf(0, "i", "š", { action = "open", pair = "[]" })
pairs.map_buf(0, "i", "đ", { action = "close", pair = "[]" })
pairs.map_buf(0, "i", "<S-Š>", { action = "open", pair = "{}" })
pairs.map_buf(0, "i", "<S-Đ>", { action = "close", pair = "{}" })
